# Generated by Django 5.0.6 on 2024-05-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("common_field", models.CharField(max_length=100)),
                ("additional_field", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
